# Generated by Django 3.1.5 on 2021-06-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.FloatField()),
                ('details', models.TextField()),
                ('stats', models.BooleanField()),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=100)),
            ],
        ),
    ]
