# Generated by Django 3.1.5 on 2021-06-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
