# Generated by Django 3.1.5 on 2021-06-16 17:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Japanis', 'Japanis'), ('Bangla', 'Bangla'), ('English', 'English'), ('Korea', 'Korea'), ('China', 'China')], default='Bangla', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='tuition/images'),
        ),
    ]
